name: flutter_localization_generator
description: A Dart command-line application for generating .arb files for localization in Flutter apps.
version: 1.1.0

environment:
  sdk: ^3.2.1

dependencies:
  args: ^2.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
